spring:
  aop:
    auto: true
    proxytarget-class: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:localhost:3306/ssm_crud
    username: root
    password: 123456
logging:
  level:
    com.murongpurple.org.interceptor: debug
server:
  port: 8080
